name: Build Armbian

on:
  workflow_dispatch:   # 手动触发
  push:                # 或者每次 push 时触发
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git gcc g++ build-essential \
            bc libncurses5-dev libssl-dev bison flex \
            libz-dev libncurses-dev \
            qemu-user-static binfmt-support debootstrap \
            device-tree-compiler python3 python3-distutils \
            python3-apt libglib2.0-dev

      - name: Build Armbian
        run: |
          ./compile.sh BOARD=rockchip64 BRANCH=current RELEASE=bookworm \
            BUILD_DESKTOP=no KERNEL_CONFIGURE=no

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: armbian-image
          path: output/images/*.img
