name: Build Armbian and Notify

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git gcc g++ build-essential \
            bc libncurses5-dev libssl-dev bison flex \
            libz-dev libncurses-dev \
            qemu-user-static binfmt-support debootstrap \
            device-tree-compiler python3 python3-distutils \
            python3-apt libglib2.0-dev

      - name: Build Armbian
        run: |
          ./compile.sh BOARD=rockchip64 BRANCH=current RELEASE=bookworm \
            BUILD_DESKTOP=no KERNEL_CONFIGURE=no

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: armbian-image
          path: output/images/*.img

      - name: Notify server via curl
        run: |
          ARTIFACT_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "Artifact URL: $ARTIFACT_URL"

          if [ -n "${{ secrets.API_TOKEN }}" ]; then
            curl -i \
              -H "Accept: application/json" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
              -X POST \
              --data "{\"status\":\"success\",\"message\":\"Armbian build completed\",\"artifact_url\":\"$ARTIFACT_URL\"}" \
              https://example.com/api/notify
          else
            echo "API_TOKEN not set, skipping notification."
          fi
